### ISSUE TITLE
Fail to start after upgrade to 11.0.1

### ISSUE THREAD

**Issue by madpipeline** [Wonderfall/dockerfiles#102]
Start log:

```
nextcloud_1     | Updating permissions in /nextcloud/config...
nextcloud_1     | Permissions in /data are correct.
nextcloud_1     | Permissions in /config are correct.
nextcloud_1     | Permissions in /apps2 are correct.
nextcloud_1     | Permissions in /etc/nginx are correct.
nextcloud_1     | Permissions in /etc/php7 are correct.
nextcloud_1     | Permissions in /var/log are correct.
nextcloud_1     | Permissions in /var/lib/nginx are correct.
nextcloud_1     | Permissions in /var/lib/redis are correct.
nextcloud_1     | Permissions in /tmp are correct.
nextcloud_1     | Permissions in /etc/s6.d are correct.
nextcloud_1     | Done updating permissions.
nextcloud_1     | Nextcloud or one of the apps require upgrade - only a limited number of commands are available
nextcloud_1     | You may use your browser or the occ upgrade command to do the upgrade
nextcloud_1     | Cannot write into "apps" directory
nextcloud_1     | This can usually be fixed by <a href="https://docs.nextcloud.com/server/11/go.php?to=admin-dir_permissions" target="_blank" rel="noreferrer">giving the webserver write access to the apps directory</a> or disabling the appstore in the config file.
nextcloud_1     | 
nextcloud_1     | An unhandled exception has been thrown:
nextcloud_1     | Exception: Environment not properly prepared. in /nextcloud/lib/private/Console/Application.php:144
nextcloud_1     | Stack trace:
nextcloud_1     | #0 /nextcloud/console.php(89): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
nextcloud_1     | #1 /nextcloud/occ(11): require_once('/nextcloud/cons...')
nextcloud_1     | #2 {main}Trying ownCloud upgrade again to work around ownCloud upgrade bug...
nextcloud_1     | Nextcloud or one of the apps require upgrade - only a limited number of commands are available
nextcloud_1     | You may use your browser or the occ upgrade command to do the upgrade
nextcloud_1     | Cannot write into "apps" directory
nextcloud_1     | This can usually be fixed by <a href="https://docs.nextcloud.com/server/11/go.php?to=admin-dir_permissions" target="_blank" rel="noreferrer">giving the webserver write access to the apps directory</a> or disabling the appstore in the config file.
nextcloud_1     | 
nextcloud_1     | An unhandled exception has been thrown:
nextcloud_1     | Exception: Environment not properly prepared. in /nextcloud/lib/private/Console/Application.php:144
nextcloud_1     | Stack trace:
nextcloud_1     | #0 /nextcloud/console.php(89): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
nextcloud_1     | #1 /nextcloud/occ(11): require_once('/nextcloud/cons...')
nextcloud_1     | #2 {main}Updating permissions...
```

docker-compose.yml file:

```
nextcloud:
  image: wonderfall/nextcloud
  restart: always
  links:
    - db_nextcloud:db_nextcloud
  environment:
    - UID=1001
    - GID=1001
    - UPLOAD_MAX_SIZE=10G
    - APC_SHM_SIZE=128M
    - OPCACHE_MEM_SIZE=128
    - CRON_PERIOD=15m
    - TZ=Europe/Bucharest

  volumes:
    - /media/500GB/NextCloud/data:/data
    - /home/ovidiu/nextcloud/config:/config
    - /home/ovidiu/nextcloud/apps:/apps2
    - /media/4TB/Poze/:/external/poze

db_nextcloud:
  image: mariadb:10
  restart: always
  volumes:
    - /home/ovidiu/nextcloud/db:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=xxx
    - MYSQL_DATABASE=nextcloud

```

I used these commands to upgrade:

```
docker-compose pull
docker-compose up -d
```

I've also tried, without a different result:

```
docker-compose stop
docker-compose rm -f
docker-compose up -d
```
