### ISSUE TITLE
[utorent] change context path + bug

### ISSUE THREAD

**Issue by zerpex** [Wonderfall/dockerfiles#131]
Hi,

Is there a way to change the context path for this app ?
If not, is it possible to add an environment variable to change it ?

Is it possible to set the uid and the guid of the user runing utorrent ?

BTW, on the readme, you mention : /usr/flood/server/db : Flood databases.
running the container with this path causes an error.

I had the container working with the following path instead : /flood-db

Here is my full docker-compose.yml file :
```
version: '2'

services:
  rutorrent:
    image: wonderfall/rtorrent-flood:latest
    container_name: rutorrent
    restart: always
    volumes:
      - /datastore/incoming:/data
      - ./files/rutorrent/db:/flood-db
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "49184:49184"
      - "49184:49184/udp"

volumes:
  files:
    driver: local
```

Thanks,
z.
