### ISSUE TITLE
Setup help :)

### ISSUE THREAD

**Issue by ghost** [Wonderfall/dockerfiles#15]
Hi, 
i'd really love to use this docker. But i am not used to properly link docker containers. And not familiar with reverse proxy stuff
Can u help me :) ? This is my compose.yml

```
image: wonderfall/nextcloud
  links:
    - db_nextcloud:db_nextcloud
  environment:
    - UID=1000
    - GID=1000
  ports:
    - "8000:80"
    - "4430:443"
  volumes:
    - /data/media/19ad4901-a651-4001-9306-425956e2c501/Cloud/data:/data
    - /root/.nextcloud/config:/config
    - /root/.nextcloud/apps:/apps2

db_nextcloud:
  image: mariadb:10
  volumes:
    - /root/.nextcloud/db:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
    - MYSQL_PASSWORD=secret

nginx:
  image: wonderfall/nginx
  container_name: nginx
  links:
    - nextcloud:nextcloud
  ports:
    - "80:8000"
    - "443:4430"
  volumes:
    - /root/.nginx/sites-enabled:/sites-enabled
    - /root/.nginx/conf:/conf.d
    - /root/.nginx/log:/var/log/nginx
    - /root/.nginx/certs:/certs
```
