### ISSUE TITLE
Nextcloud config not in /config volume

### ISSUE THREAD

**Issue by madpipeline** [Wonderfall/dockerfiles#16]
I've used the wonderfall/nextcloud image with the docker-compose given with small modifications. However, after starting the container, the directory used as the config volume is empty.

Docker-compose.yml:

```
nextcloud:
  image: wonderfall/nextcloud
  restart: always
  links:
    - db_nextcloud:db_nextcloud
  environment:
    - UID=1001
    - GID=1001
  volumes:
    - /media/500GB/nextcloud/data:/data
    - /home/ovidiu/nextcloud/config:/config
    - /home/ovidiu/nextcloud/apps:/apps2
    - /media/4TB/poze/:/external/poze

db_nextcloud:
  image: mariadb:10
  restart: always
  volumes:
    - /home/ovidiu/nextcloud/db:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=xxx
    - MYSQL_DATABASE=nextcloud
```

```
$ ls -lah /home/ovidiu/nextcloud/config
total 0
drwxrwxr-x. 1 media  media   0 iul  6 13:12 .
drwxrwxr-x. 1 ovidiu ovidiu 60 iul  6 13:38 ..
```

From what I see in the [run.sh](https://github.com/Wonderfall/dockerfiles/blob/master/nextcloud/9.0/run.sh) script, you are not sym-linking the config directory, but copying it's contents. Why?
