### ISSUE TITLE
[Nextcloud] Problem with setup. Help wanted.

### ISSUE THREAD

**Issue by Martinius** [Wonderfall/dockerfiles#162]
Hello,
sorry to bother you with this, but I can't get the server to work with your nginx package. I only get a 502 error. It also seems that no configuration data for nextcloud is created the config folger is always empty. Also the folder are always owned by root even if the UID differs.  Here is my docker-compose.yml file:

```
                                                                         
nextcloud:
  image: wonderfall/nextcloud
  container_name: nextcloud
  links:
    - nextcloud-db:nextcloud-db   # If using MySQL
#    - solr:solr                   # If using Nextant
    - redis:redis                 # If using Redis
  environment:
    - UID=1001
    - GID=1001
  volumes:
    - /mnt/nextcloud/data:/data
    - /mnt/nextcloud/config:/config
    - /mnt/nextcloud/apps:/apps2
    - /mnt/nextcloud/themes:/nextcloud/themes

# If using MySQL
nextcloud-db:
  image: mariadb:10
  container_name: nextcloud-db
  volumes:
    - /mnt/nextcloud/db:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=pas
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
    - MYSQL_PASSWORD=pas


# If using Nextant
#solr:
#  image: solr:6-alpine
#  container_name: solr
#  volumes:
#    - /mnt/docker/solr:/opt/solr/server/solr/mycores
#  entrypoint:
#    - docker-entrypoint.sh
#    - solr-precreate
#    - nextant

# If using Redis
redis:
  image: redis:alpine
  container_name: redis
  volumes:
    - /mnt/docker/redis:/data

nginx:
  image: wonderfall/boring-nginx
  container_name: nginx
  links:
    - nextcloud:nextcloud
  ports:
    - "80:8000"
    - "443:4430"
  environment:
    - GID = 1001
    - UID = 1001
  volumes:
    - /mnt/docker/nginx/sites-enabled:/sites-enabled
    - /mnt/docker/nginx/conf:/conf.d
    - /mnt/docker/nginx/log:/var/log/nginx
    - /mnt/docker/nginx/certs:/certs
```

And here is my nginx nextcloud.conf that I created with your setup script:
```
server {
  listen 8000;
  server_name mcloud.dnsup.net;
  return 301 https://$host$request_uri;
}

server {
  listen 4430 ssl http2;
  server_name mcloud.dnsup.net;

  ssl_certificate /certs/fullchain.pem;
  ssl_certificate_key /certs/privkey.pem;

  include /etc/nginx/conf/ssl_params;
  include /etc/nginx/conf/headers_params;

  #add_header Strict-Transport-Security "max-age=<HSTS_MAX_AGE>;<HSTS_SUBDOMAINS><HSTS_PRELOAD>";
  client_max_body_size 10G;

  #auth_basic "Who's this?";
  #auth_basic_user_file /passwds/<NAME>.htpasswd;

  location / {
    proxy_pass http://nextcloud:8888;
    include /etc/nginx/conf/proxy_params;
  }
}
```
I created the certs with letsencrypt and they seem to be working, but as stated I only get a 502 error.  This is the docker compose startup log:

```
[root@Central-Server mnt]# docker-compose up -d nextcloud-db
Starting nextcloud-db
[root@Central-Server mnt]# docker-compose up -d 
nextcloud-db is up-to-date
Starting redis
Starting nextcloud
Starting nginx
[root@Central-Server mnt]# docker-compose logs
Attaching to nginx, nextcloud, nextcloud-db, redis
nextcloud       | Updating permissions...
nextcloud       | Updating permissions in /nextcloud...
nextcloud       | Updating permissions...
nextcloud       | Updating permissions in /nextcloud...
redis           | 1:C 29 Mar 23:54:37.418 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis           |                 _._                                                  
redis           |            _.-``__ ''-._                                             
redis           |       _.-``    `.  `_.  ''-._           Redis 3.2.8 (00000000/0) 64 bit
redis           |   .-`` .-```.  ```\/    _.,_ ''-._                                   
redis           |  (    '      ,       .-`  | `,    )     Running in standalone mode
redis           |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redis           |  |    `-._   `._    /     _.-'    |     PID: 1
redis           |   `-._    `-._  `-./  _.-'    _.-'                                   
nextcloud-db    | 2017-03-29 23:54:38 140504797890496 [Note] mysqld (mysqld 10.1.22-MariaDB-1~jessie) starting as process 1 ...
nextcloud-db    | 2017-03-29 23:54:39 140504797890496 [Note] InnoDB: Using mutexes to ref count buffer pool pages
nextcloud-db    | 2017-03-29 23:54:39 140504797890496 [Note] InnoDB: The InnoDB memory heap is disabled
nextcloud-db    | 2017-03-29 23:54:39 140504797890496 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
nextcloud-db    | 2017-03-29 23:54:39 140504797890496 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
nextcloud-db    | 2017-03-29 23:54:39 140504797890496 [Note] InnoDB: Compressed tables use zlib 1.2.8
nextcloud-db    | 2017-03-29 23:54:39 140504797890496 [Note] InnoDB: Using Linux native AIO
nextcloud-db    | 2017-03-29 23:54:39 140504797890496 [Note] InnoDB: Using generic crc32 instructions
nextcloud-db    | 2017-03-29 23:54:39 140504797890496 [Note] InnoDB: Initializing buffer pool, size = 256.0M
nextcloud-db    | 2017-03-29 23:54:39 140504797890496 [Note] InnoDB: Completed initialization of buffer pool
nextcloud-db    | 2017-03-29 23:54:39 140504797890496 [Note] InnoDB: Highest supported file format is Barracuda.
nextcloud-db    | 2017-03-29 23:54:39 140504797890496 [Note] InnoDB: 128 rollback segment(s) are active.
nextcloud-db    | 2017-03-29 23:54:39 140504797890496 [Note] InnoDB: Waiting for purge to start
nextcloud-db    | 2017-03-29 23:54:39 140504797890496 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.35-80.0 started; log sequence number 1616849
redis           |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis           |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
redis           |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redis           |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis           |  |    `-._`-._        _.-'_.-'    |                                  
redis           |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redis           |       `-._    `-.__.-'    _.-'                                       
redis           |           `-._        _.-'                                           
redis           |               `-.__.-'                                               
redis           | 
redis           | 1:M 29 Mar 23:54:37.427 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis           | 1:M 29 Mar 23:54:37.427 # Server started, Redis version 3.2.8
redis           | 1:M 29 Mar 23:54:37.428 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis           | 1:M 29 Mar 23:54:37.428 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis           | 1:M 29 Mar 23:54:37.428 * DB loaded from disk: 0.000 seconds
redis           | 1:M 29 Mar 23:54:37.428 * The server is now ready to accept connections on port 6379
redis           | 1:signal-handler (1490831837) Received SIGTERM scheduling shutdown...
nextcloud-db    | 2017-03-29 23:54:39 140504020780800 [Note] InnoDB: Dumping buffer pool(s) not yet started
nextcloud-db    | 2017-03-29 23:54:39 140504797890496 [Note] Plugin 'FEEDBACK' is disabled.
nextcloud-db    | 2017-03-29 23:54:40 140504797890496 [Note] Server socket created on IP: '::'.
nextcloud-db    | 2017-03-29 23:54:40 140504797890496 [Warning] 'proxies_priv' entry '@% root@43ca3913ef80' ignored in --skip-name-resolve mode.
nextcloud-db    | 2017-03-29 23:54:40 140504797890496 [Note] mysqld: ready for connections.
nextcloud-db    | Version: '10.1.22-MariaDB-1~jessie'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
nextcloud-db    | 2017-03-29 23:57:17 140504797022976 [Note] mysqld: Normal shutdown
nextcloud-db    | 
nextcloud-db    | 2017-03-29 23:57:17 140504797022976 [Note] Event Scheduler: Purging the queue. 0 events
nextcloud-db    | 2017-03-29 23:57:17 140504003995392 [Note] InnoDB: FTS optimize thread exiting.
nextcloud-db    | 2017-03-29 23:57:17 140504797022976 [Note] InnoDB: Starting shutdown...
nextcloud-db    | 2017-03-29 23:57:17 140504797022976 [Note] InnoDB: Waiting for page_cleaner to finish flushing of buffer pool
nextcloud-db    | 2017-03-29 23:57:19 140504797022976 [Note] InnoDB: Shutdown completed; log sequence number 1616859
nextcloud-db    | 2017-03-29 23:57:19 140504797022976 [Note] mysqld: Shutdown complete
nextcloud-db    | 
nextcloud-db    | 2017-03-29 23:57:35 140510481094592 [Note] mysqld (mysqld 10.1.22-MariaDB-1~jessie) starting as process 1 ...
nextcloud-db    | 2017-03-29 23:57:35 140510481094592 [Note] InnoDB: Using mutexes to ref count buffer pool pages
nextcloud-db    | 2017-03-29 23:57:35 140510481094592 [Note] InnoDB: The InnoDB memory heap is disabled
nextcloud-db    | 2017-03-29 23:57:35 140510481094592 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
redis           | 1:M 29 Mar 23:57:17.758 # User requested shutdown...
redis           | 1:M 29 Mar 23:57:17.758 * Saving the final RDB snapshot before exiting.
redis           | 1:M 29 Mar 23:57:17.798 * DB saved on disk
redis           | 1:M 29 Mar 23:57:17.798 # Redis is now ready to exit, bye bye...
redis           | 1:C 29 Mar 23:58:20.354 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis           |                 _._                                                  
redis           |            _.-``__ ''-._                                             
redis           |       _.-``    `.  `_.  ''-._           Redis 3.2.8 (00000000/0) 64 bit
redis           |   .-`` .-```.  ```\/    _.,_ ''-._                                   
redis           |  (    '      ,       .-`  | `,    )     Running in standalone mode
redis           |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redis           |  |    `-._   `._    /     _.-'    |     PID: 1
redis           |   `-._    `-._  `-./  _.-'    _.-'                                   
nextcloud-db    | 2017-03-29 23:57:35 140510481094592 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
redis           |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
nextcloud-db    | 2017-03-29 23:57:35 140510481094592 [Note] InnoDB: Compressed tables use zlib 1.2.8
nextcloud-db    | 2017-03-29 23:57:35 140510481094592 [Note] InnoDB: Using Linux native AIO
redis           |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
redis           |   `-._    `-._`-.__.-'_.-'    _.-'                                   
nextcloud-db    | 2017-03-29 23:57:35 140510481094592 [Note] InnoDB: Using generic crc32 instructions
nextcloud-db    | 2017-03-29 23:57:35 140510481094592 [Note] InnoDB: Initializing buffer pool, size = 256.0M
redis           |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis           |  |    `-._`-._        _.-'_.-'    |                                  
nextcloud-db    | 2017-03-29 23:57:35 140510481094592 [Note] InnoDB: Completed initialization of buffer pool
nextcloud-db    | 2017-03-29 23:57:35 140510481094592 [Note] InnoDB: Highest supported file format is Barracuda.
redis           |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redis           |       `-._    `-.__.-'    _.-'                                       
nextcloud-db    | 2017-03-29 23:57:35 140510481094592 [Note] InnoDB: 128 rollback segment(s) are active.
nextcloud-db    | 2017-03-29 23:57:35 140510481094592 [Note] InnoDB: Waiting for purge to start
redis           |           `-._        _.-'                                           
nextcloud-db    | 2017-03-29 23:57:35 140510481094592 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.35-80.0 started; log sequence number 1616859
redis           |               `-.__.-'                                               
nextcloud-db    | 2017-03-29 23:57:36 140509704062720 [Note] InnoDB: Dumping buffer pool(s) not yet started
nextcloud-db    | 2017-03-29 23:57:36 140510481094592 [Note] Plugin 'FEEDBACK' is disabled.
redis           | 
nextcloud-db    | 2017-03-29 23:57:36 140510481094592 [Note] Server socket created on IP: '::'.
nextcloud-db    | 2017-03-29 23:57:36 140510481094592 [Warning] 'proxies_priv' entry '@% root@43ca3913ef80' ignored in --skip-name-resolve mode.
nextcloud-db    | 2017-03-29 23:57:36 140510481094592 [Note] mysqld: ready for connections.
nextcloud-db    | Version: '10.1.22-MariaDB-1~jessie'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
redis           | 1:M 29 Mar 23:58:20.363 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis           | 1:M 29 Mar 23:58:20.363 # Server started, Redis version 3.2.8
redis           | 1:M 29 Mar 23:58:20.363 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis           | 1:M 29 Mar 23:58:20.363 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis           | 1:M 29 Mar 23:58:20.363 * DB loaded from disk: 0.000 seconds
redis           | 1:M 29 Mar 23:58:20.363 * The server is now ready to accept connections on port 6379



```

Thank you very much for your help.
