### ISSUE TITLE
[Nextcloud] Error on update

### ISSUE THREAD

**Issue by WebDucer** [Wonderfall/dockerfiles#178]
Hello.

We have a very small installtion of Nextcloud with 10 users and about 100 files at the current time.

After the last Update (image id: cebb5c11ee00) the instance shows to update nextcloud manually. After executing:

```bash
docker exec -ti nextcloud occ upgrade
```

and a long waiting time (over10 minutes), we got the following error output:

```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'UPDATE `oc_filecache` SET `etag` = 'xxx' WHERE (`etag` = '') OR (`etag` IS NULL)':

SQLSTATE[HY000](): General error: 1206 The total number of locks exceeds the lock table size
Update failed
```

What can we do to repair the instance?

**Comment by WebDucer** [comment]
I increased `innodb-buffer-pool-size` (as described in some posts) to 256MB but without success. It took longer (over 30 minutes) for the exception, but nothing else.

I also tried `maintanance:repair` with similar result.

```
> docker exec -ti nextcloud occ maintenance:repair
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Failed to load repair step for dav: Repair step 'OCA\DAV\Migration\FixBirthdayCalendarComponent' is unknown
Failed to load repair step for dav: Repair step 'OCA\DAV\Migration\CalDAVRemoveEmptyValue' is unknown
Failed to load repair step for user_ldap: Repair step 'OCA\User_LDAP\Migration\UUIDFixInsert' is unknown
 - Repair MySQL collation
 - Repair mime types
 - Repair legacy storages
 - Remove asset cache
     - Asset cache cleared.
 - Generate ETags for file where no ETag is present.

  [Doctrine\DBAL\Exception\DriverException]                                                                                  
  An exception occurred while executing 'UPDATE `oc_filecache` SET `etag` = 'xxx' WHERE (`etag` = '') OR (`etag` IS NULL)':  
  SQLSTATE[HY000]: General error: 1206 The total number of locks exceeds the lock table size                                 

  [Doctrine\DBAL\Driver\PDOException]                                                         
  SQLSTATE[HY000]: General error: 1206 The total number of locks exceeds the lock table size  

  [PDOException]                                                                              
  SQLSTATE[HY000]: General error: 1206 The total number of locks exceeds the lock table size  

maintenance:repair [--include-expensive]
```

Is there a way to fix this?

My compose file looks like following:

```yaml
...
    nextcloud_db:
        image: mariadb:10.1.22
        container_name: nextcloud-db
        environment:
            MYSQL_ROOT_PASSWORD: "db-root-secret-pw"
            MYSQL_DATABASE: "nextcloud"
            MYSQL_USER: "nextcloud"
            MYSQL_PASSWORD: "db-secret-pw"
        command: mysqld --innodb-buffer-pool-size=256M
        volumes:
            - nextcloud_db_data:/var/lib/mysql
    
    nextcloud:
        image: wonderfall/nextcloud:11.0
        container_name: nextcloud
        hostname: cloud.example.com
        depends_on:
            - https_proxy
            - nextcloud_db
        environment:
            VIRTUAL_HOST: "cloud.example.com -> http://nextcloud:8888"
            UPLOAD_MAX_SIZE: 5G
            ADMIN_USER: "Admin"
            ADMIN_PASSWORD: "cloud-secret-pw"
            DB_TYPE: "mysql"
            DB_NAME: "nextcloud"
            DB_USER: "nextcloud"
            DB_PASSWORD: "db-secret-pw"
            DB_HOST: "nextcloud_db"
        volumes:
            - nextcloud_data:/data
            - nextcloud_config:/config
            - nextcloud_apps:/apps2
            - nextcloud_redis:/var/lib/redis
...
```
