### ISSUE TITLE
collarbora support

### ISSUE THREAD

**Issue by maxhoheiser** [Wonderfall/dockerfiles#181]
hi do you plan to add collabora docker container support with your nextcloud container, and your docker-compose file?

**Comment by schleyk** [comment]
Collabora works fine with the "collabora/code" image, 
docker-compoes.yml:
```
  collabora:
     restart: always
     image: collabora/code
     tty: true
     cap_add:
     - MKNOD
     environment:
     - "domain=cloud\\.nextcloud\\.com|cloud\\.example\\.org"
     ports:
     - "9980:9980"
```
NGINX Reverse Proxy Config:
```
  location ^~ /loleaflet {
    proxy_pass https://docker.lan:9980;
    proxy_set_header Host $http_host;
  }

  location ^~ /hosting/discovery {
    proxy_pass https://docker.lan:9980;
    proxy_set_header Host $http_host;
  }

  location ^~ /lool {
    proxy_pass https://docker.lan:9980;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
  }
```
