### ISSUE TITLE
[Nextant]

### ISSUE THREAD

**Issue by maxhoheiser** [Wonderfall/dockerfiles#184]
Hi I have a problem with nextant:
My docker-compose.yml:
````
nextcloud:
  image: wonderfall/nextcloud
  links:
    - nextcloud-db:nextcloud-db
    - solr:solr                   
    - redis:redis               
    - collabora:collabora
  container_name: nextcloud
  environment:
    - UID=1000
    - GID=1000
    - UPLOAD_MAX_SIZE=10G
    - APC_SHM_SIZE=128M
    - OPCACHE_MEM_SIZE=128
    - CRON_PERIOD=60m
    - TZ=Europe/Vienna
    - ADMIN_USER=# Don't set to configure through browser
    - ADMIN_PASSWORD=# Don't set to configure through browser
    - DOMAIN=localhost
    - DB_TYPE=mysql
    - DB_NAME=nextcloud
    - DB_USER=nextcloud
    - DB_PASSWORD=
    - DB_HOST=nextcloud-db
    - VIRTUAL_PORT=8888
    - VIRTUAL_HOST=
  ports:
    - 8888:8888
  volumes:
    - /tank/cloud/data:/data
    - /media/ssd500gb/docker/nextcloud/config:/config
    - /media/ssd500gb/docker/nextcloud/apps:/apps2
    - /media/ssd500gb/docker/nextcloud/themes:/nextcloud/themes 
    - /media/ssd500gb/docker/nextcloud/config/ca-bundle.crt:/nextcloud/config/ca-bundle.crt
    - /media/ssd500gb/docker/nextcloud/letsencrypt:/var/www
    
nextcloud-db:
  image: mariadb:10
  container_name: nextcloud-db
  volumes:
    - /media/ssd500gb/docker/nextcloud/db:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=
    - MYSQL_DATABASE=
    - MYSQL_USER=
    - MYSQL_PASSWORD=

solr:
  image: solr:6.5-alpine
  container_name: nextcloud-solr
  volumes:
    - /media/ssd500gb/docker/nextcloud/solr:/opt/solr/server/solr/mycores
  entrypoint:
    - docker-entrypoint.sh
    - solr-precreate
    - nextant

redis:
  image: redis:alpine
  container_name: nextcloud-redis
  volumes:
    - /media/ssd500gb/docker/nextcloud/redis:/etc/loolwsd/

collabora:
  image: collabora/code
  container_name: nextcloud-collabora
  volumes:
    - /media/ssd500gb/docker/nextcloud/collabora:/etc/loolwsd/
    - /media/ssd500gb/docker/nextcloud/letsencrypt:/var/www
  ports:
    - 9980:9980
  cap_add:
   - MKNOD
  environment:
   - domain=....
   - VIRTUAL_HOST=
   - VIRTUAL_PORT=9980
   - VIRTUAL_PROTO=http
````

If I want to connect to solr via the nextcloud admin panel I get:
![solr](https://cloud.githubusercontent.com/assets/15856892/25785518/fc7f8780-3382-11e7-8171-55b8cc92883c.PNG)

do I have to confiugre the core manualy?
