### ISSUE TITLE
Debian 9 + nextcloud 12 + local-persisst volume plg

### ISSUE THREAD

**Issue by Berndinox** [Wonderfall/dockerfiles#227]
Container stuck at:
```
Updating permissions...
Updating permissions in /nextcloud...
```

Node:
```
docker info
Containers: 8
 Running: 8
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 17.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local local-persist
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
```

List "nextcloud" folder:
```
root@myhostname# docker exec -it 51355ea8ec5e ls /nextcloud -lah
total 168
drwxr-xr-x    1 root     root        4.0K Sep 13 15:43 .
drwxr-xr-x    1 root     root        4.0K Sep 13 15:43 ..
-rw-r--r--    1 nobody   nogroup     2.6K Sep 12 01:00 .htaccess
-rw-r--r--    1 nobody   nogroup      163 Sep 12 01:00 .user.ini
drwxr-xr-x    1 nobody   nogroup     4.0K Sep 12 01:02 3rdparty
-rw-r--r--    1 nobody   nogroup     8.7K Sep 12 01:00 AUTHORS
drwxr-xr-x   36 nobody   nogroup     4.0K Sep 12 01:00 apps
lrwxrwxrwx    1 root     root           6 Sep 13 15:43 apps2 -> /apps2
drwxr-xr-x    1 nobody   nogroup     4.0K Sep 13 15:43 config
-rw-r--r--    1 nobody   nogroup     4.0K Sep 12 01:00 console.php
drwxr-xr-x   16 nobody   nogroup     4.0K Sep 12 01:02 core
-rw-r--r--    1 nobody   nogroup     4.9K Sep 12 01:00 cron.php
-rw-r--r--    1 nobody   nogroup    40.1K Sep 12 01:00 db_structure.xml
-rw-r--r--    1 nobody   nogroup      179 Sep 12 01:00 index.html
-rw-r--r--    1 nobody   nogroup     2.7K Sep 12 01:00 index.php
drwxr-xr-x    3 nobody   nogroup     4.0K Sep 12 01:00 l10n
drwxr-xr-x    1 xfs      xfs         4.0K Sep 12 01:00 lib
-rw-r--r--    1 nobody   nogroup      283 Sep 12 01:00 occ
drwxr-xr-x    2 nobody   nogroup     4.0K Sep 12 01:00 ocs
drwxr-xr-x    2 nobody   nogroup     4.0K Sep 12 01:00 ocs-provider
-rw-r--r--    1 nobody   nogroup     3.1K Sep 12 01:00 public.php
-rw-r--r--    1 nobody   nogroup     5.2K Sep 12 01:00 remote.php
drwxr-xr-x    4 nobody   nogroup     4.0K Sep 12 01:00 resources
-rw-r--r--    1 nobody   nogroup       26 Sep 12 01:00 robots.txt
drwxr-xr-x   14 nobody   nogroup     4.0K Sep 12 01:00 settings
-rw-r--r--    1 nobody   nogroup     2.1K Sep 12 01:00 status.php
drwxr-xr-x    3 xfs      xfs         4.0K Sep 13 15:43 themes
drwxr-xr-x    2 nobody   nogroup     4.0K Sep 12 01:00 updater
-rw-r--r--    1 nobody   nogroup      434 Sep 12 01:02 version.php
```
ps aux:
```
PID   USER     TIME   COMMAND
    1 root       0:00 {run.sh} /bin/sh /usr/local/bin/run.sh
   13 root       0:01 chown -R 33:33 /nextcloud
   26 root       0:00 ps aux
```

compose:
```
  nextcloud:
    image: wonderfall/nextcloud:daily
    environment:
      - DB_NAME=nextcloud
      - DB_PASSWORD=SECRET
      - DB_USER=nextcloud
      - DB_HOST=mysql
      - DB_TYPE=mysql
      - ADMIN_USER=root
      - ADMIN_PASSWORD=SECRET
      - DOMAIN=FQDN
      - UID=33
      - GID=33
    volumes:
      - data:/data
      - apps:/apps2
      - config:/config
      - session:/php/session
      - themes:/nextcloud/themes
    deploy:
      replicas: 1
      labels:
        - "traefik.port=8888"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.rule=Host:FQDN"
        - "traefik.backend=nextcloud"
        - "traefik.frontend.entryPoints=http,https"
      update_config:
        parallelism: 1
        delay: 30s
        monitor: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 60s
    networks:
      proxy:
        aliases:
          - nextcloud
      default:
    depends_on:
      - mysql
      - redis
```

Same issue with the stable (wonderfall/nextcloud)
