### ISSUE TITLE
[nextcloud] Supporting full text search with Nextant

### ISSUE THREAD

**Issue by jazzdd86** [Wonderfall/dockerfiles#82]
A great feature is the full text search of all your documents. To get it up and running, there are some prerequisites you would need to implement.
See installation instructions: [https://github.com/nextcloud/nextant/wiki](https://github.com/nextcloud/nextant/wiki).
Would be nice to see it implemented in this great image.

**Comment by ghost** [comment]
no need to implement it in the docker - please keep it as clean as possible.
just set-up a second solr container and connect it - as i did :)

**Comment by jazzdd86** [comment]
Gret idea, could you give me an example of your solr container setup?

**Comment by ghost** [comment]
```
nextcloud_solr:
    image: solr:alpine
    container_name: nextcloud_solr
    ports:
      - "8983:8983"
    volumes:
      - .solr:/opt/solr/server/solr/mycores
```
https://hub.docker.com/_/solr/

**Comment by jazzdd86** [comment]
Thanks,
I adapted your example to my setup and integrated it to my compose file. I linked nextcloud and solr container together. I can wget http://solr:8983/solr from nextcloud bash, but in admin console of nextcloud nextant says it cannot ping given address. What am I doing wrong?

```
nextcloud:
    container_name: nextcloud
    restart: always
    links:
        - mysql
        - redis
        - solr
    volumes:
        - ./data:/data
        - ./config:/config
        - ./apps:/apps2
    image: wonderfall/nextcloud

redis:
    container_name: nextcloud_redis
    restart: always
    image: redis

mysql:
    container_name: nextcloud_mariadb
    restart: always
    volumes:
        - ./db:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=pass
        - MYSQL_USER=owncloud
        - MYSQL_PASSWORD=pass
        - MYSQL_DATABASE=owncloud
    command: --binlog-format=MIXED
    image: mariadb

solr:
    container_name: nextcloud_solr
    volumes:
      - ./solr:/opt/solr/server/solr/mycores
    image: solr:alpine

```

![image](https://cloud.githubusercontent.com/assets/10222385/21718115/5f7ba4ae-d415-11e6-97f8-d195fefb4ab0.png)
